---
title: "Incomplete Data Analysis: Assignment 2"
author: s2445245
date: March 20, 2023
output:
  pdf_document: default
---
\section{Question 1}
\subsection{(1a)}


\
\subsection{(1b)}


\
\subsection{(1c)}

\
\
\section{Question 2}
\subsection{(2a)}

\
\subsection{(2b)}
```{r}
# loading data
load("dataex2.rdata")
load("dataex4.rdata")
load("dataex5.rdata")
```

```{r}
# Determine the maximum likelihood estimate of mu based on the data available 
# in the file dataex2.Rdata. Consider sigma2 known and equal to 1.5^2
set.seed(1)

mean.all <- mean(dataex2$X)
mean.obs <- mean(dataex2$X[which(dataex2$X>4)])
sigma2 <- 1.5
X <- dataex2$X
R <- dataex2$R

n.log.ll <- function(mu, sigma2, x, r) {
  log.ll <- 0
  for (i in 1:length(x)){
    log.ll <- log.ll +(r[i] * dnorm(x[i], mu, sqrt(sigma2)) + 
                         (1 - r[i]) * pnorm(x[i], mu, sqrt(sigma2)))
  }
  -log.ll
}

result.mle <- suppressWarnings(optim(mean.all, n.log.ll, 
                                 sigma2 = sigma2, x = X, r = R))

print(paste('The maximum likelihood estimate of mu based on the data is',
            result.mle$par))
```

\
\section{Question 3}
\subsection{(3a)}

\

\subsection{(3b)}

\

\subsection{(3c)}


\
\
\section{Question 4}
```{r}

```

\
\
\section{Question 5}
\subsection{(5a)}
```{r}

```

\
\subsection{(5b)}
```{r}

```
